version: '3'

services:
    mariadb:
        image: mariadb:10.6.17
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./data:/var/lib/mysql
        ports:
            - 3306:3306